apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-portfolio
  template:
    metadata:
      labels:
        app: devops-portfolio
    spec:
      containers:
        - name: devops-portfolio
          image: kingacr.azurecr.io/devops-portfolio:latest
          ports:
            - containerPort: 8080
